name: Pip

on: [push, pull_request]

jobs:
  build:
    name: Build with pip on windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install third parties
        run: |
          set VCPKG_BUILD_TYPE=release
          vcpkg install boost-filesystem --triplet x64-windows
          vcpkg version
          ls "C:\vcpkg\installed\x64-windows\bin\"

      - name: Build and install
        env:
          SKBUILD_CMAKE_DEFINE: "VCPKG_TARGET_TRIPLET=x64-windows;CMAKE_TOOLCHAIN_FILE='c:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake'"
        run: |
          pip wheel --verbose .
