name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # MacOS x86_64
          - os: macos-13
            python: 310
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-14
            python: 310
            platform_id: macosx_arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Homebrew
        run: |
          echo 'Updating Homebrew...'
          brew update
          echo 'Installing dependencies...'
          brew install curl

      - name: Download and Install Boost
        run: |
          echo 'Downloading Boost...'
          curl -LO 'https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.gz'
          echo 'Extracting Boost...'
          tar xf boost_1_87_0.tar.gz
          cd boost_1_87_0
          echo 'Bootstrapping Boost...'
          ./bootstrap.sh
          echo 'Building and installing Boost...'
          sudo ./b2 --with-filesystem install

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_BUILD: cp310-*
          MACOSX_DEPLOYMENT_TARGET: 10.13
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
